// HomeLens AI - 앱 전체 스타일 객체
// CSSProperties 타입으로 TypeScript 타입 안전성 보장
// S 객체 안에 모든 컴포넌트 스타일 포함

import { CSSProperties } from "react";
import { COLORS } from "./colors";

// 전체 스타일 객체
// wrap: 앱 전체 래퍼
// phone: 모바일 화면 컨테이너
// nav: 개발용 화면 전환 버튼 영역
// scr: 화면 컴포넌트 래퍼
// sc: 스크롤 가능한 화면 컨텐츠 영역
// bar: 상단 헤더 바
// scard: 가격 정보 카드
// tabbar: 탭 버튼 영역
// cht*: 차트 관련 스타일
// r*: AI 리포트 관련 스타일
export const S: Record<string, CSSProperties> = {
  wrap: {
    padding: "12px 0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    background: COLORS.bgSecondary,
    minHeight: "100vh",
  },
  nav: { display: "flex", gap: 5, flexWrap: "wrap", justifyContent: "center" },
  nb: {
    fontSize: 11,
    padding: "5px 11px",
    borderRadius: 8,
    border: `0.5px solid ${COLORS.borderSecondary}`,
    background: COLORS.bgSecondary,
    color: COLORS.textSecondary,
    cursor: "pointer",
  },
  nbOn: {
    background: COLORS.textPrimary,
    color: COLORS.bgPrimary,
    borderColor: "transparent",
  },
  phone: {
    width: 320,
    background: COLORS.bgPrimary,
    borderRadius: 32,
    border: `1.5px solid ${COLORS.borderSecondary}`,
    overflow: "hidden",
  },
  scr: { display: "flex", flexDirection: "column" },
  sc: { overflowY: "auto", maxHeight: 650, scrollbarWidth: "none" },
  bar: {
    display: "flex",
    alignItems: "center",
    padding: "13px 16px",
    borderBottom: `0.5px solid ${COLORS.borderTertiary}`,
    gap: 10,
    flexShrink: 0,
  },
  bk: {
    fontSize: 22,
    color: COLORS.textPrimary,
    cursor: "pointer",
    lineHeight: 1,
  },
  logo: { fontSize: 19, fontWeight: 500, color: COLORS.textPrimary, flex: 1 },
  sb: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    background: COLORS.bgPrimary,
    border: `1px solid ${COLORS.borderSecondary}`,
    borderRadius: 11,
    padding: "9px 12px",
    margin: "14px 16px 0",
  },
  sbInput: {
    flex: 1,
    border: "none",
    outline: "none",
    fontSize: 13,
    color: COLORS.textPrimary,
    background: "transparent",
  },
  dd: {
    background: COLORS.bgPrimary,
    border: `0.5px solid ${COLORS.borderSecondary}`,
    borderRadius: 11,
    margin: "5px 16px 0",
    overflow: "hidden",
  },
  ddi: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 12px",
    cursor: "pointer",
    borderBottom: `0.5px solid ${COLORS.borderTertiary}`,
  },
  ddn: { fontSize: 13, fontWeight: 500, color: COLORS.textPrimary },
  dds: { fontSize: 11, color: COLORS.textSecondary },
  dda: { fontSize: 15, color: COLORS.textTertiary, marginLeft: "auto" },
  mclb: {
    margin: "10px 16px 0",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  mct: { fontSize: 12, fontWeight: 500, color: COLORS.textPrimary },
  mcs: { fontSize: 10, color: COLORS.textTertiary },
  mtab: {
    display: "flex",
    background: COLORS.bgSecondary,
    borderRadius: 10,
    padding: 3,
    margin: "6px 16px 0",
  },
  mt: {
    flex: 1,
    textAlign: "center",
    padding: "6px 2px",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 10,
    color: COLORS.textSecondary,
  },
  mtOn: {
    background: COLORS.bgPrimary,
    color: COLORS.textPrimary,
    fontWeight: 500,
    border: `0.5px solid ${COLORS.borderTertiary}`,
  },
  mw: {
    margin: "6px 16px 0",
    borderRadius: 14,
    overflow: "hidden",
    border: `0.5px solid ${COLORS.borderTertiary}`,
  },
  sec: { padding: "10px 16px 0" },
  st: {
    fontSize: 13,
    fontWeight: 500,
    color: COLORS.textPrimary,
    marginBottom: 7,
  },
  ir: {
  display: "flex",
  flexDirection: "column", 
  gap: 4,                   
  padding: "7px 0",
  borderBottom: `0.5px solid ${COLORS.borderTertiary}`,
  },
  id: { fontSize: 10, color: COLORS.textTertiary, minWidth: 44, paddingTop: 1 },
  it: { fontSize: 11, color: COLORS.textPrimary, lineHeight: 1.5 },
  ib: {
    fontSize: 9,
    fontWeight: 500,
    padding: "1px 6px",
    borderRadius: 8,
    marginRight: 3,
  },
  scard: {
    margin: "10px 16px 0",
    background: COLORS.bgPrimary,
    border: `0.5px solid ${COLORS.borderSecondary}`,
    borderRadius: 14,
    padding: 13,
  },
  sr: { display: "flex" },
  si: { flex: 1 },
  sp: { width: "0.5px", background: COLORS.borderTertiary, margin: "0 10px" },
  sl: { fontSize: 10, color: COLORS.textSecondary, marginBottom: 3 },
  sv: { fontSize: 14, fontWeight: 500, color: COLORS.textPrimary },
  svsm: { fontSize: 12, fontWeight: 500, color: COLORS.textPrimary },
  sd: { fontSize: 10, color: "#27500A", marginTop: 1 },
  sdv: { height: "0.5px", background: COLORS.borderTertiary, margin: "10px 0" },
  amenityList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    marginTop: 6,
  },
  amenityRow: { display: "flex", alignItems: "center", gap: 6 },
  amenityDot: { width: 7, height: 7, borderRadius: "50%", flexShrink: 0 },
  amenityCat: { fontSize: 10, color: COLORS.textSecondary, minWidth: 44 },
  amenityName: {
    fontSize: 11,
    fontWeight: 500,
    color: COLORS.textPrimary,
    flex: 1,
  },
  amenityDist: { fontSize: 10, color: COLORS.textTertiary },
  subwayTag: {
    background: "#EAF3DE",
    color: "#27500A",
    fontSize: 10,
    fontWeight: 500,
    padding: "3px 9px",
    borderRadius: 20,
  },
  legend: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    padding: "8px 10px",
    background: COLORS.bgPrimary,
    borderTop: `0.5px solid ${COLORS.borderTertiary}`,
  },
  legendItem: { display: "flex", alignItems: "center", gap: 4 },
  legendDot: { width: 8, height: 8, borderRadius: "50%" },
  legendLabel: { fontSize: 9, color: COLORS.textSecondary },
  tabbar: {
    display: "flex",
    background: COLORS.bgSecondary,
    borderRadius: 10,
    padding: 3,
    margin: "10px 16px 0",
  },
  ti: {
    flex: 1,
    textAlign: "center",
    padding: "6px 3px",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 10,
    color: COLORS.textSecondary,
  },
  tiOn: {
    background: COLORS.bgPrimary,
    color: COLORS.textPrimary,
    fontWeight: 500,
    border: `0.5px solid ${COLORS.borderTertiary}`,
  },
  tc: { padding: "10px 16px 24px" },
  cp: {
    margin: "8px 16px 0",
    background: COLORS.bgPrimary,
    border: `0.5px solid ${COLORS.borderTertiary}`,
    borderRadius: 13,
    padding: 12,
  },
  cpt: { fontSize: 12, fontWeight: 500, color: COLORS.textPrimary },
  cps: { fontSize: 10, color: COLORS.textSecondary, margin: "2px 0 8px" },
  ci: {
    display: "flex",
    alignItems: "center",
    padding: "8px 0",
    borderTop: `0.5px solid ${COLORS.borderTertiary}`,
    cursor: "pointer",
  },
  cil: { flex: 1 },
  cin: { fontSize: 12, fontWeight: 500, color: COLORS.textPrimary },
  cit: { fontSize: 10, color: COLORS.textSecondary, marginTop: 1 },
  cibBadge: {
    fontSize: 10,
    color: COLORS.textSecondary,
    background: COLORS.bgSecondary,
    padding: "3px 9px",
    borderRadius: 20,
    fontWeight: 500,
  },
  ic: {
    background: COLORS.bgPrimary,
    border: `0.5px solid ${COLORS.borderTertiary}`,
    borderRadius: 11,
    padding: 10,
    marginBottom: 7,
  },
  im: { display: "flex", alignItems: "center", gap: 5, marginBottom: 4 },
  icd: { fontSize: 10, color: COLORS.textTertiary },
  ict: { fontSize: 11, color: COLORS.textPrimary, lineHeight: 1.5 },
  ptog: { display: "flex", gap: 5, marginBottom: 8 },
  ptb: {
    fontSize: 10,
    padding: "4px 10px",
    borderRadius: 20,
    border: `0.5px solid ${COLORS.borderSecondary}`,
    background: COLORS.bgSecondary,
    color: COLORS.textSecondary,
    cursor: "pointer",
  },
  ptbOn: {
    background: COLORS.textPrimary,
    color: COLORS.bgPrimary,
    borderColor: "transparent",
  },
  rtog: { display: "flex", gap: 4, marginBottom: 8 },
  rtb: {
    fontSize: 10,
    padding: "4px 9px",
    borderRadius: 20,
    border: `0.5px solid ${COLORS.borderSecondary}`,
    background: COLORS.bgSecondary,
    color: COLORS.textSecondary,
    cursor: "pointer",
  },
  rtbOn: {
    borderColor: COLORS.borderPrimary,
    color: COLORS.textPrimary,
    fontWeight: 500,
  },
  chartTitle: {
    fontSize: 11,
    fontWeight: 500,
    color: COLORS.textPrimary,
    marginBottom: 6,
  },
  chtOuter: {
    background: COLORS.bgPrimary,
    border: `0.5px solid ${COLORS.borderTertiary}`,
    borderRadius: 11,
    padding: "14px 8px 8px",
  },
  chtBars: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    height: 90,
    marginBottom: 6,
  },
  chtSep: {
    height: "0.5px",
    background: COLORS.borderTertiary,
    margin: "0 0 5px",
  },
  chtLbls: { display: "flex", justifyContent: "space-between" },
  cc: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: 1,
    height: "100%",
    justifyContent: "flex-end",
  },
  cv: {
    fontSize: 8,
    color: COLORS.textTertiary,
    marginBottom: 4,
    whiteSpace: "nowrap",
  },
  cbw: { display: "flex", alignItems: "flex-end", width: "62%", height: 68 },
  cb: { width: "100%", borderRadius: "2px 2px 0 0" },
  cl: { fontSize: 8, color: COLORS.textTertiary, flex: 1, textAlign: "center" },
  s3: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 6,
    marginTop: 10,
  },
  s3b: {
    background: COLORS.bgSecondary,
    borderRadius: 10,
    padding: "12px 8px",
    textAlign: "center",
  },
  s3l: { fontSize: 10, color: COLORS.textSecondary, marginBottom: 6 },
  s3v: { fontSize: 14, fontWeight: 500, color: COLORS.textPrimary },
  rstart: { textAlign: "center", padding: "20px 12px" },
  rst: {
    fontSize: 14,
    fontWeight: 500,
    color: COLORS.textPrimary,
    marginBottom: 5,
    marginTop: 10,
  },
  rss: {
    fontSize: 11,
    color: COLORS.textSecondary,
    lineHeight: 1.6,
    marginBottom: 16,
  },
  rbtn: {
    background: COLORS.textPrimary,
    color: COLORS.bgPrimary,
    border: "none",
    borderRadius: 10,
    padding: "9px 20px",
    fontSize: 12,
    fontWeight: 500,
    cursor: "pointer",
  },
  rsum: {
    background: COLORS.bgSecondary,
    border: `0.5px solid ${COLORS.borderSecondary}`,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  rsuml: { fontSize: 10, color: COLORS.textSecondary, marginBottom: 4 },
  rsumq: {
    fontSize: 12,
    fontWeight: 500,
    color: COLORS.textPrimary,
    lineHeight: 1.6,
    fontStyle: "italic",
  },
  rsec: {
    background: COLORS.bgPrimary,
    border: `0.5px solid ${COLORS.borderTertiary}`,
    borderRadius: 11,
    padding: 12,
    marginBottom: 7,
  },
  rset: {
    fontSize: 11,
    fontWeight: 500,
    color: COLORS.textPrimary,
    marginBottom: 7,
    paddingBottom: 6,
    borderBottom: `0.5px solid ${COLORS.borderTertiary}`,
  },
  rbody: { fontSize: 11, color: COLORS.textSecondary, lineHeight: 1.7 },
  disc: {
    background: COLORS.bgSecondary,
    borderRadius: 9,
    padding: 10,
    fontSize: 9,
    color: COLORS.textTertiary,
    lineHeight: 1.75,
    marginTop: 6,
  },
  rdate: {
    fontSize: 9,
    color: COLORS.textTertiary,
    textAlign: "right",
    marginTop: 4,
  },
  listItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: COLORS.bgPrimary,
    border: `0.5px solid ${COLORS.borderTertiary}`,
    borderRadius: 11,
    padding: 10,
    marginBottom: 7,
    cursor: "pointer",
  },
};
