"""create_initial_tables

Revision ID: 5f5837a9aef4
Revises: 
Create Date: 2026-05-07 12:05:07.711888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5837a9aef4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_address', sa.String(length=300), nullable=False),
    sa.Column('legal_dong_code', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('impact_type', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('ref_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_markers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('marker_type', sa.String(length=20), nullable=False),
    sa.Column('avg_price', sa.BigInteger(), nullable=True),
    sa.Column('price_level', sa.String(length=10), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('jeonse_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.String(length=50), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_regions',
    sa.Column('news_id', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('news_id', 'region_id')
    )
    op.create_table('places',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('kakao_place_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('place_type', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('avg_sale_price', sa.BigInteger(), nullable=True),
    sa.Column('avg_jeonse_price', sa.BigInteger(), nullable=True),
    sa.Column('avg_monthly_rent', sa.BigInteger(), nullable=True),
    sa.Column('avg_monthly_deposit', sa.BigInteger(), nullable=True),
    sa.Column('jeonse_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recent_trade_count', sa.Integer(), nullable=True),
    sa.Column('price_stability_grade', sa.String(length=10), nullable=False),
    sa.Column('price_level', sa.String(length=15), nullable=False),
    sa.Column('data_base_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'data_base_date', name='uq_price_snapshot_region_date')
    )
    op.create_table('price_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('deal_type', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('min_price', sa.BigInteger(), nullable=False),
    sa.Column('avg_price', sa.BigInteger(), nullable=False),
    sa.Column('max_price', sa.BigInteger(), nullable=False),
    sa.Column('total_trade_count', sa.Integer(), nullable=False),
    sa.Column('recent_trade_count', sa.Integer(), nullable=False),
    sa.Column('trade_signal', sa.String(length=10), nullable=False),
    sa.Column('data_base_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'deal_type', 'period', 'data_base_date', name='uq_price_stats_region_deal_period_date')
    )
    op.create_table('price_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('deal_type', sa.String(length=10), nullable=False),
    sa.Column('avg_price', sa.BigInteger(), nullable=False),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('fail_reason', sa.Text(), nullable=True),
    sa.Column('data_base_date', sa.Date(), nullable=True),
    sa.Column('cached_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('section_key', sa.String(length=30), nullable=False),
    sa.Column('section_title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_sections')
    op.drop_table('reports')
    op.drop_table('price_trends')
    op.drop_table('price_stats')
    op.drop_table('price_snapshots')
    op.drop_table('places')
    op.drop_table('news_regions')
    op.drop_table('news_keywords')
    op.drop_table('map_markers')
    op.drop_table('locations')
    op.drop_table('issues')
    op.drop_table('regions')
    op.drop_table('news')
    # ### end Alembic commands ###