apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi
  namespace: homelens
  annotations:
    # terraform output -json | jq -r '.fastapi_role_arn.value'
    eks.amazonaws.com/role-arn: "arn:aws:iam::611058323802:role/homelens-dev-fastapi-api-role"
