name: Deploy Backend to ECR & EKS

on:
  push:
    branches: [dev]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: 611058323802.dkr.ecr.eu-west-3.amazonaws.com
          ECR_REPOSITORY: homelens-fastapi
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-west-3 --name homelens-dev-eks

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: homelens-fastapi
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/fastapi \
            fastapi=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -n homelens
          kubectl rollout status deployment/fastapi -n homelens

      - name: Run Alembic Migration
        run: |
          kubectl exec -n homelens \
            $(kubectl get pod -n homelens \
              -l app=fastapi \
              -o jsonpath='{.items[0].metadata.name}') \
            -- alembic upgrade head